In [1]:
import os
import matplotlib.pyplot as plt
#!pip install joblib
import joblib
import numpy as np
plt.style.use("fivethirtyeight")

  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)


In [18]:
class Perceptron:
    def __init__(self, eta:float=None,epochs:int=None):
        self.weights=np.random.randn(3)*1e-4
        self.eta=eta#learning rate
        self.epochs=epochs#iterations
    def fit(self, X, y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X_with bias:\n{X_with_bias}")

In [19]:
obj=Perceptron(eta=0.01,epochs=10)


In [20]:
y=np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [17]:
obj.weights

array([-6.40690608e-06, -1.61858204e-04,  1.10793268e-04])

In [21]:
obj.fit(X,y)

X_with bias:
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [11]:
np.c_[X, -np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])