In [52]:
import os
import matplotlib.pyplot as plt
#!pip install joblib
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")

In [71]:
class Perceptron:
    def __init__(self, eta:float=None,epochs:int=None):
        self.weights=np.random.randn(3)*1e-4
        self.eta=eta#learning rate
        self.epochs=epochs#iterations
    def _z_outcome(self, inputs,weights):
        return np.dot(inputs,weights)
    def activation_function(self,z):
        return np.where(z>0,1,0)
    def fit(self, X, y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X_with bias:\n{X_with_bias}")
        for epoch in range(self.epochs):
            z=self._z_outcome(X_with_bias, self.weights)
            print(f"Z is:\n{z}")
            y_hat=self.activation_function(z)
            #print(f"y:\n{y}")
            print(f"y_hat:\n{y_hat}")
            self.error=self.y-y_hat
            print(f"Error:\n{self.error}")
            self.weights=self.weights+self.eta*np.dot(X_with_bias.T,self.error)
            print(f"Updated weights after epochs:{epoch+1}/{self.epochs}:\n{self.weights}")
    def predict(self, X):
        X_with_bias=np.c_[X,-np.ones((len(X),1))]
        z=self._z_outcome(X_with_bias, self.weights)
        print(f"Prediction of z:\n{z}")
        return self.activation_function(z)
        
            
            
    

In [72]:

OR={"x1":[0,0,1,1],
   "x2":[0,1,0,1],
   "y":[0,1,1,1]}
df_OR=pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [73]:

def prepare_data(df, target_col="y"):
    X=df.drop(target_col, axis=1)
    y=df[target_col]
    return X,y

In [76]:
AND={"x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,0,0,1]}
df_AND=pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [77]:
X,y=prepare_data(df_AND)
ETA=0.1
EPOCHS=10
model_or=Perceptron(eta=ETA,epochs=EPOCHS)
model_or.fit(X,y)


X_with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Z is:
[6.19423137e-05 5.93186310e-06 1.05910714e-04 4.99002636e-05]
y_hat:
[1 1 1 1]
Error:
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights after epochs:1/10:
[-0.09995603 -0.10005601  0.29993806]
Z is:
[-0.29993806 -0.39999407 -0.39989409 -0.4999501 ]
y_hat:
[0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after epochs:2/10:
[ 4.39684005e-05 -5.60104506e-05  1.99938058e-01]
Z is:
[-0.19993806 -0.19999407 -0.19989409 -0.1999501 ]
y_hat:
[0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after epochs:3/10:
[0.10004397 0.09994399 0.09993806]
Z is:
[-9.99380577e-02  5.93186310e-06  1.05910714e-04  1.00049900e-01]
y_hat:
[0 1 1 1]
Error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights after epochs:4/10:
[ 4.39684005e-05 -5.60104506e-05  2.99938058e-01]
Z is:
[-0.29993806 -0.29999407 -0.29989409 -0.2999501 ]
y_hat:
[0

In [36]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [17]:
obj.weights

array([-6.40690608e-06, -1.61858204e-04,  1.10793268e-04])

In [21]:
obj.fit(X,y)

X_with bias:
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [11]:
np.c_[X, -np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

In [23]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
np.c_[X, -np.ones((4,1))]

In [24]:
np.random.randn(3)*1e-4

array([ 2.45397184e-05, -4.68636428e-05,  1.34638918e-04])

In [25]:
np.dot(np.c_[X, -np.ones((4,1))],np.random.randn(3)*1e-4)

array([-1.64961068e-05, -1.64961068e-05, -1.64961068e-05, -1.64961068e-05])

In [26]:
np.c_[X, -np.ones((4,1))].T

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [-1., -1., -1., -1.]])

In [27]:
np.c_[X, -np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])