In [52]:
import os
import matplotlib.pyplot as plt
#!pip install joblib
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")

In [71]:
class Perceptron:
    def __init__(self, eta:float=None,epochs:int=None):
        self.weights=np.random.randn(3)*1e-4
        self.eta=eta#learning rate
        self.epochs=epochs#iterations
    def _z_outcome(self, inputs,weights):
        return np.dot(inputs,weights)
    def activation_function(self,z):
        return np.where(z>0,1,0)
    def fit(self, X, y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X_with bias:\n{X_with_bias}")
        for epoch in range(self.epochs):
            z=self._z_outcome(X_with_bias, self.weights)
            print(f"Z is:\n{z}")
            y_hat=self.activation_function(z)
            #print(f"y:\n{y}")
            print(f"y_hat:\n{y_hat}")
            self.error=self.y-y_hat
            print(f"Error:\n{self.error}")
            self.weights=self.weights+self.eta*np.dot(X_with_bias.T,self.error)
            print(f"Updated weights after epochs:{epoch+1}/{self.epochs}:\n{self.weights}")
    def predict(self, X):
        X_with_bias=np.c_[X,-np.ones((len(X),1))]
        z=self._z_outcome(X_with_bias, self.weights)
        print(f"Prediction of z:\n{z}")
        return self.activation_function(z)
        
            
            
    

In [72]:

OR={"x1":[0,0,1,1],
   "x2":[0,1,0,1],
   "y":[0,1,1,1]}
df_OR=pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [73]:

def prepare_data(df, target_col="y"):
    X=df.drop(target_col, axis=1)
    y=df[target_col]
    return X,y

In [74]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [75]:
X,y=prepare_data(df_OR)
ETA=0.1
EPOCHS=10
model_or=Perceptron(eta=ETA,epochs=EPOCHS)
model_or.fit(X,y)


X_with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Z is:
[0.00024148 0.00031186 0.00025889 0.00032927]
y_hat:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epochs:1/10:
[1.74084514e-05 7.03809534e-05 9.97585175e-02]
Z is:
[-0.09975852 -0.09968814 -0.09974111 -0.09967073]
y_hat:
[0 0 0 0]
Error:
0    0
1    1
2    1
3    1
Name: y, dtype: int64
Updated weights after epochs:2/10:
[ 0.20001741  0.20007038 -0.20024148]
Z is:
[0.20024148 0.40031186 0.40025889 0.60032927]
y_hat:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epochs:3/10:
[ 0.20001741  0.20007038 -0.10024148]
Z is:
[0.10024148 0.30031186 0.30025889 0.50032927]
y_hat:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epochs:4/10:
[ 0.20001741  0.20007038 -0.00024148]
Z is:
[2.41482505e-04 2.00311863e-01 2.00258891e-01 4.00329272e-01]
y_hat:
[1 1 1 1]
Error:
0   -1
1    0
2    0
3   

In [36]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [17]:
obj.weights

array([-6.40690608e-06, -1.61858204e-04,  1.10793268e-04])

In [21]:
obj.fit(X,y)

X_with bias:
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [11]:
np.c_[X, -np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

In [23]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
np.c_[X, -np.ones((4,1))]

In [24]:
np.random.randn(3)*1e-4

array([ 2.45397184e-05, -4.68636428e-05,  1.34638918e-04])

In [25]:
np.dot(np.c_[X, -np.ones((4,1))],np.random.randn(3)*1e-4)

array([-1.64961068e-05, -1.64961068e-05, -1.64961068e-05, -1.64961068e-05])

In [26]:
np.c_[X, -np.ones((4,1))].T

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [-1., -1., -1., -1.]])

In [27]:
np.c_[X, -np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])